package com.example.composewithredux.redux// Generated by KSP
import kotlin.Any
import kotlin.Boolean
import kotlin.String
import kotlin.collections.List

public data class AppState2(
  public val areas: List<Area>,
  public val name: String?,
  public val flag: Boolean,
)

public fun rootReducer2(state: AppState2, action: Any): AppState2 = AppState2(
   areas = areaReducer(state.areas, action),
   name = nameReducer(state.name, action),
   flag = flagReducer(state.flag, action),
)
